import { hashPassword } from './password';

export const SEED_PASSWORD = 'DefyraSecurity2026!';

// Fixed synchronous seed hash generated by hashPassword for "DefyraSecurity2026!"
// Salt: 88ff72cb25055caee996f01bb4ddf69c
// Derived key: scryptSync("DefyraSecurity2026!", salt, 64)
export const DEFAULT_FOUNDER_PASSWORD_HASH =
  '88ff72cb25055caee996f01bb4ddf69c:4cf50a8b92b67f13919ad7eb2c2c01ca701c3bfd69a2444db6f9f30b91e2b5e282bf83f6f1c4943fcfcbffc325da734f19b22295c5264b3efee179f8263dd494';
